project:
  type: website

website:
  title: "skovbogit.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: statistics.qmd
        text: Statistics

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

